### ISSUE TITLE
EPIC #235: Front-end reworking

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#235]
**Problem**

The front-end is a very organic JavaScript construct. It does not use MVC, nor does it have proper abstractions over the REST API. Also it is not stateless (i.e. you cannot refresh the page without losing information).

**Solution**

Use a proper MVC framework for the front-end and rework the way configuration properties are stored so the page is actually refreshable. Also the MVC makes front-end code a lot more testable.

**Subtasks**
- [ ] #243 use MVC framework
- [x] #237 configuration as part of servable object (JS)
- [ ] #238 replace document cache by REST call
- [ ] #244 add JS tests

I need to check if there are no TODOs left I created on the way (Scala and JS).
