### ISSUE TITLE
Spark Package

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#279]
### Task

http://spark-packages.org/register
### Acceptance Criteria
- [ ] Package is visible on http://spark-packages.org
- [ ] Package can be included via `--package` option when launching Spark (https://github.com/databricks/sbt-spark-package)
- [ ] Including DDS as a dependency through spark packages sbt plugin works and is documented in README

**Comment by FRosner** [comment]
As my AWS account is expiring, I need to hurry up with this one :)

I should package it also backwards for previous releases, best going back to 2.x or even all of them? Maybe the latest minor release is enough?
