### ISSUE TITLE
[EPIC-61] Upgrade to Spark 1.3

### ISSUE THREAD

**Issue by FRosner** [FRosner/spawncamping-dds#61]
- [x] Upgrade dependency (#63)
- [x] Check release notes and create tickets for features
- [x] API for Data frame (#155)
- [x] Change default scala build version to 2.10 (#156)

This will probably end up in DDS 2.x because it breaks the API when working with Spark 1.2. Does it make sense to backport patches to 1.x branch?

https://spark.apache.org/docs/latest/sql-programming-guide.html#upgrading-from-spark-sql-10-12-to-13
